Patchflow that generates architecture diagram
patched-codes/patchwork pull request #1022
Opened 2024-11-13 16:39 UTC by plon-Susk7

## PR Checklist

- [x] The commit message follows our guidelines: [Code of conduct](https://github.com/patched-codes/patchwork/blob/main/CODE_OF_CONDUCT.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [ ] Does this PR introduce a breaking change?
- [x] Include PR in release notes?

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring
- [ ] Build /CI
- [ ] Documentation
- [ ] Others

## What is the current behavior?

There's no patchflow to generate architecture diagrams for a repo.

Issue Number: #951

## What is the new behavior?

The newly made GenerateDiagram patchflow generates mermaid markdown that visualizes overall architecture of the Repo

## Other information

2024-11-15 01:56 UTC, CTY-git requested changes
Can you add a CI test again @plon-Susk7 . Thanks.

2024-11-15 05:38 UTC, plon-Susk7 commented
> Can you add a CI test again @plon-Susk7 . Thanks.

Done :)

2024-11-18 06:13 UTC, CTY-git requested changes

2024-11-18 06:13 UTC, CTY-git commented on .github/workflows/test.yml
> +          poetry run patchwork GenerateDiagrams --log debug \
The patchflow name is `GenerateDiagram`, not `GenerateDiagrams` as used here.

2024-11-21 05:44 UTC, plon-Susk7 commented
hi @CTY-git sorry to bug you. Could you please review this PR?

2024-12-02 03:56 UTC, CTY-git approved these changes

2024-12-02 03:56 UTC, merged